### ISSUE TITLE
home work #5: footer mismatch

### ISSUE THREAD

**Issue by eko24ive** [zozo89/home#1]
Here is how your footer looks:
![image](https://cloud.githubusercontent.com/assets/25591824/22869213/0123d184-f1a6-11e6-9ce4-3e9bc66c5ed2.png)

And this is desirable result:
![image](https://cloud.githubusercontent.com/assets/25591824/22869215/0bc55978-f1a6-11e6-9f71-012a13476eef.png)

Please fix this.

**Comment by zozo89** [comment]
fixed
