### ISSUE TITLE
home work #4: style mismatch for navigation

### ISSUE THREAD

**Issue by eko24ive** [zozo89/home#3]
Here is how your navigation looks
![image](https://cloud.githubusercontent.com/assets/25591824/22869100/39813914-f1a5-11e6-9323-13ff5c1c7f62.png)

And this is desirable result:
![image](https://cloud.githubusercontent.com/assets/25591824/22869092/243cc15e-f1a5-11e6-97d4-776491e27e85.png)

Please fix this.

**Comment by zozo89** [comment]
Fixed
